"""Shared config/constants for jh-clio-lib.

Credentials come from ~/.env.jh, the platform-wide env file generated by
jh-law-scripts/tools/bootstrap_env.py from Secret Manager (PLATFORM_OVERVIEW.md §5)
— do not invent a project-local .env here.
"""
from __future__ import annotations

import os
from pathlib import Path

GCP_PROJECT = "jh-law-rc-clio-personal"

# Verified 2026-07-19 against the live servers block of
# https://docs.developers.clio.com/openapi.json (US region production server).
CLIO_BASE = "https://app.clio.com/api/v4"
CLIO_TOKEN_URL = "https://app.clio.com/oauth/token"

LAWMATICS_BASE = "https://api.lawmatics.com/v1"

ENV_JH_PATH = Path.home() / ".env.jh"


def _load_env_jh() -> dict[str, str]:
    values: dict[str, str] = {}
    if not ENV_JH_PATH.exists():
        return values
    for line in ENV_JH_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        values[key.strip()] = val.strip()
    return values


_ENV_JH = _load_env_jh()


def get(key: str, default: str | None = None) -> str | None:
    """Look up a credential/config value: real env var first, then ~/.env.jh."""
    return os.environ.get(key) or _ENV_JH.get(key) or default


CLIO_MANAGE_CLIENT_ID = get("CLIO_MANAGE_CLIENT_ID")
CLIO_MANAGE_CLIENT_SECRET = get("CLIO_MANAGE_CLIENT_SECRET")
LM_ACCESS_TOKEN = get("LM_ACCESS_TOKEN")
